### ISSUE TITLE
Header/Metadata Decoding

### ISSUE THREAD

**Issue by sgodwincs** [dgriffen/flif.rs#1]
I made a reply to your reddit post and I did a quick comparison of some of the header decoding that I had with yours. Here are a couple of things I noticed:

 - ~~[header.rs#L67](https://github.com/dgriffen/flif.rs/blob/master/src/flif/components/header.rs#L67) will panic on debug if underflow occurs. I'm not sure if this is a big deal or not though.~~ After thinking about, I don't think handling overflows/underflows is important in debug mode.
 - [metadata.rs#L47](https://github.com/dgriffen/flif.rs/blob/master/src/flif/components/metadata.rs#L47): The spec mentions that there is currently only one non-optional chunk (0x00), so maybe it would be better to return an error if it is between 0..32 and is not 0.
 - Also, for the metadata, the spec also says:

> If a decoder encounters an unknown optional chunk, it should proceed decoding

whereas this implementation will error out on any unknown optional chunk without checking if the chunk is critical or not (by seeing if the first letter is uppercase).

Let me know if I'm wrong somewhere. If you agree, I can make a PR.

**Comment by dgriffen** [comment]
Both of those suggestions sound fine. Anything to bring us more in line with the spec is good.

**Comment by dgriffen** [comment]
Closed via #2
