### ISSUE TITLE
Grayscale support

### ISSUE THREAD

**Issue by newpavlov** [dgriffen/flif.rs#19]
Hi and thank you for you work!

Any updates on grayscale support? I am using flif to store raw 8-bit RGGB images and I would love to make my tool which works with those images pure-Rust (currently I bind to `libflif_dec.so`), so I am looking forward to improvements for this use-case!

**Comment by dgriffen** [comment]
Grayscale support is on the timeline once I have all the transformations implemented. Although I can change that priority if there is enough need.
