### ISSUE TITLE
Relicense under dual MIT/Apache

### ISSUE THREAD

**Issue by dgriffen** [dgriffen/flif.rs#22]
It was suggested in #21 to relicense under dual MIT/Apache. I personally don't have any objections to this so I'm opening this issue to start the discussion. As far as I understand it I need signoff from all contributers of "creative works" to the project. It's not entirely clear what that constitutes but I'll be requiring signoffs from any contributors with over 100 lines changed. Any other contributors are free to voice their consent or objections as well, which I will take into account.

**Required**
- [x] @newpavlov 
- [ ] @matthiaskrgr 
- [x] @dgriffen

**Optional**
- [x] @willstott101 
- [x] @sgodwincs

**Comment by willstott101** [comment]
No optional objection from me

**Comment by newpavlov** [comment]
No objections.

**Comment by sgodwincs** [comment]
No objections.

**Comment by dgriffen** [comment]
@matthiaskrgr Ping

**Comment by matthiaskrgr** [comment]
@dgriffen Sorry for the delay, I somehow missed previous notice.

No objections.
