### ISSUE TITLE
Huge memory usage on small input

### ISSUE THREAD

**Issue by newpavlov** [dgriffen/flif.rs#27]
Via #26 

The following 52 byte input triggers growing memory usage (more than several gigabytes):
```Rust
b"FLIF41\x1f\xff\xff\xf8\x00\x00 \x00\x00\x02\x00\x00\x00\x037\xec\x03Lh\x00\x00\x00\x03\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xffF9";
```

**Comment by dgriffen** [comment]
Probably due to the maniac tree. I'll ask around in the FLIF-Hub gitter to figure out what a sensible limit on the size of a maniac tree is.

**Comment by newpavlov** [comment]
The issue was huge number of pixels not MANIAC decoder, so #28 fixed it.
