### ISSUE TITLE
Valid images throw errors

### ISSUE THREAD

**Issue by newpavlov** [dgriffen/flif.rs#42]
The following images were generated with the official `flif` tool and can be decoded by it and `libflif_dec` without any problems, while this crate throws errors on them:
- [invalid_tid.flfi](http://rgho.st/private/7kvyVJHPM/88f4b357d43f7e9741b016ee045b6057) "Invalid transformation identifier read, possibly corrupt file"
- [invalid_tree.flif](http://rgho.st/private/6TwY9Hm4G/c4e4573f90ca4213ee428633ae03471a) "Invalid maniac tree"

**Comment by dgriffen** [comment]
Yeah sorry, I've been busy the past month. I'll get to it as soon as I am able.
