### ISSUE TITLE
RGBA image results in "invalid maniac tree" for master branch

### ISSUE THREAD

**Issue by newpavlov** [dgriffen/flif.rs#55]
Example image can be downloaded from [here](https://github.com/dgriffen/flif.rs/files/2707292/incor.zip). Code in the `master` branch results in "invalid maniac tree", while `v0.3.0` published on crates.io correctly decompresses it. I guess we have introduced a bug somewhere together with optimizations.

**Comment by dgriffen** [comment]
Well at least we have a version of our code that works! That will make debugging a lot easier, I was getting tired of having to setup C++ for debugging. The maniac and near-zero code hasn't changed with the optimizations so I'm guessing either a transformation broke things or the pvec changes did.

**Comment by newpavlov** [comment]
Looks like regression was introduced by me in #45.
